//USER
export const XEM_CHI_TIET='XEM_CHI_TIET';
export const DANG_KY='DANG_KY';
export const LUU_MANGSP='LUU_MANGSP';
export const LUU_TAIKHOAN='LUU_TAIKHOAN';
export const KIEM_TRA_DANG_KY='KIEM_TRA_DANG_KY';
export const THEM_TAI_KHOAN='THEM_TAI_KHOAN';
export const ADMIN_LOGIN= 'ADMIN_LOGIN';
export const ADMIN_LOGOUT= 'ADMIN_LOGOUT';
export const USER_LOGIN='USER_LOGIN';
export const IS_USER_LOGIN='IS_USER_LOGIN';
export const IS_USER_LOGOUT='IS_USER_LOGOUT';
export const XOA_USER='XOA_USER';
export const USER_UPDATE_TRANGTHAI=' USER_UPDATE_TRANGTHAI';
export const USER_RECOVER_TRANGTHAI='USER_RECOVER_TRANGTHAI';
export const USER_DUOCCHON='USER_DUOCCHON';
export const UPDATE_USER='UPDATE_USER';
export const UPDATE_PASSWORD='UPDATE_PASSWORD';
export const UPDATE_PASSWORD_USER='UPDATE_PASSWORD_USER';
export const UPDATE_OTP='UPDATE_OTP';
//SANPHAM

export const UPDATE_SANPHAM_TRANGTHAI='UPDATE_SANPHAM_TRANGTHAI';
export const RECOVER_SANPHAM_TRANGTHAI='RECOVER_SANPHAM_TRANGTHAI';
export const THEM_SAN_PHAM = 'THEM_SAN_PHAM';
export const SAN_PHAM_DUOC_CHON = 'SAN_PHAM_DUOC_CHON';
export const SAN_PHAM_VUA_XEM = 'SAN_PHAM_VUA_XEM';